export const SEED_BARBERS = [
  {
    id: 'barber-1',
    name: 'Andi Pratama',
    specialty: 'Fade & Classic Cut',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Andi',
    rating: 4.8,
    reviewCount: 124,
    experience: '5 tahun',
  },
  {
    id: 'barber-2',
    name: 'Budi Santoso',
    specialty: 'Beard Styling',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Budi',
    rating: 4.6,
    reviewCount: 98,
    experience: '4 tahun',
  },
  {
    id: 'barber-3',
    name: 'Citra Wijaya',
    specialty: 'Modern & Coloring',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Citra',
    rating: 4.9,
    reviewCount: 156,
    experience: '7 tahun',
  },
  {
    id: 'barber-4',
    name: 'Dedi Kurniawan',
    specialty: 'Kids & Family Cut',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dedi',
    rating: 4.5,
    reviewCount: 87,
    experience: '3 tahun',
  },
  {
    id: 'barber-5',
    name: 'Eko Ramadhan',
    specialty: 'Premium Grooming',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Eko',
    rating: 4.7,
    reviewCount: 112,
    experience: '6 tahun',
  },
]

export const SEED_SERVICES = [
  {
    id: 'service-1',
    name: 'Potong Rambut',
    description: 'Potong rambut klasik atau modern sesuai gaya Anda',
    price: 50000,
    duration: 30,
    icon: 'mdi:content-cut',
  },
  {
    id: 'service-2',
    name: 'Cukur Jenggot',
    description: 'Trim dan styling jenggot profesional',
    price: 35000,
    duration: 30,
    icon: 'mdi:razor-double-edge',
  },
  {
    id: 'service-3',
    name: 'Cuci & Styling',
    description: 'Cuci rambut, blow dry, dan styling ringan',
    price: 40000,
    duration: 30,
    icon: 'mdi:hair-dryer',
  },
  {
    id: 'service-4',
    name: 'Coloring',
    description: 'Pewarnaan rambut dengan produk premium',
    price: 150000,
    duration: 60,
    icon: 'mdi:palette',
  },
  {
    id: 'service-5',
    name: 'Paket Lengkap',
    description: 'Potong, cukur jenggot, cuci, dan styling',
    price: 120000,
    duration: 60,
    icon: 'mdi:star-circle',
  },
]

export const SEED_USERS = [
  {
    id: 'user-demo',
    name: 'Demo User',
    email: 'demo@kokobarber.com',
    phone: '081234567890',
    password: 'demo123',
    completedBookings: 10,
    createdAt: '2025-01-15T08:00:00.000Z',
  },
]

export const SEED_BOOKINGS = [
  {
    id: 'booking-seed-1',
    userId: 'user-demo',
    barberId: 'barber-1',
    serviceId: 'service-1',
    date: '2026-06-01',
    timeSlot: '14:00',
    status: 'completed',
    originalPrice: 50000,
    finalPrice: 25000,
    discountApplied: true,
    paymentMethod: 'mock',
    paidAt: '2026-06-01T13:55:00.000Z',
    rated: true,
    rating: 5,
    review: 'Pelayanan sangat memuaskan!',
    createdAt: '2026-06-01T10:00:00.000Z',
  },
  {
    id: 'booking-seed-2',
    userId: 'user-demo',
    barberId: 'barber-3',
    serviceId: 'service-5',
    date: '2026-06-10',
    timeSlot: '16:30',
    status: 'ongoing',
    originalPrice: 120000,
    finalPrice: 60000,
    discountApplied: true,
    paymentMethod: 'mock',
    paidAt: '2026-06-10T16:00:00.000Z',
    rated: false,
    rating: null,
    review: null,
    createdAt: '2026-06-08T09:00:00.000Z',
  },
]
